# Generated by Django 4.0.4 on 2022-06-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('fee', models.IntegerField()),
                ('description', models.CharField(max_length=90)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=50)),
                ('eligibility', models.CharField(max_length=50)),
                ('exam_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('username', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('questionbank_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('question_paper', models.ImageField(upload_to='')),
                ('answer_key', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'question_bank',
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=30)),
                ('doj', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=90)),
                ('experience', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('staffid', models.IntegerField()),
                ('studid', models.IntegerField()),
                ('eventid', models.IntegerField()),
                ('qbankid', models.IntegerField()),
                ('examid', models.IntegerField()),
                ('qstid', models.IntegerField()),
                ('studexamid', models.IntegerField()),
                ('resultid', models.IntegerField()),
                ('feeid', models.IntegerField()),
                ('reviewid', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
        migrations.CreateModel(
            name='student_admission',
            fields=[
                ('student_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('admission_date', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=90)),
                ('street', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=90)),
                ('dob', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=90)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
            options={
                'db_table': 'student_admission',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_appli_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=30)),
                ('admission_date', models.CharField(max_length=30)),
                ('house_name', models.CharField(max_length=90)),
                ('street', models.CharField(max_length=90)),
                ('district', models.CharField(max_length=90)),
                ('dob', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=50)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=150)),
                ('review_date', models.CharField(max_length=30)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student_admission')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('result_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student_admission')),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('question_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exam')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='fee_payment',
            fields=[
                ('payment_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('fee', models.CharField(max_length=30)),
                ('payment_date', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('account_no', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student_admission')),
            ],
            options={
                'db_table': 'fee_payment',
            },
        ),
        migrations.CreateModel(
            name='exam_registration',
            fields=[
                ('student_exam_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student_admission')),
            ],
            options={
                'db_table': 'exam_registration',
            },
        ),
    ]
