# Generated by Django 4.0.4 on 2022-07-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='ansid',
            field=models.IntegerField(default=34),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='option_error',
            fields=[
                ('answer_id', models.CharField(max_length=90, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=30)),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.result')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student_admission')),
            ],
            options={
                'db_table': 'option_error',
            },
        ),
    ]
