# Generated by Django 4.0.4 on 2022-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_staff_address_staff_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='district',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='street',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
    ]
