# Generated by Django 4.0.4 on 2022-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_option_error_result_id_option_error_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_error',
            name='date',
            field=models.CharField(default='fg', max_length=30),
            preserve_default=False,
        ),
    ]
